### ISSUE TITLE
Exiting the game while in editor mode exits to the editor

### ISSUE THREAD

**Issue by Nikoichu** [ElectricGun/Toggle-Editor-Mode#2]
Again, a fault of how the editor mode works, however this might introduce a few problems that I haven't tested fully yet, like:
-Is the map getting saved properly when exiting this way?
-Is there a way to avoid this behavior? Like automatic way to turn off the editor mode when the user clicks "quit game"?

**Comment by ElectricGun** [comment]
Noted.

**Comment by ElectricGun** [comment]
Editor will now be disabled while user is on pause menu.
