### ISSUE TITLE
toggle button is overlaping(maybe wronge word?) the Command Mode button on mobile

### ISSUE THREAD

**Issue by dekiitteh** [ElectricGun/Toggle-Editor-Mode#3]
i tried it on mobile but now im using a potato laptop and i did not screenshot but it looked like this
![charge gorilla ;)](https://user-images.githubusercontent.com/110713540/219618505-4429278b-3b32-4db9-baea-1ab25702ce32.png)

***it is not blue i just used it because it looked out of place and to tell it is from this mod.**
edit : grammer fix

**Comment by ElectricGun** [comment]
It should be fine now after rewrite
