### ISSUE TITLE
Editor "Edit in-game" crash

### ISSUE THREAD

**Issue by JojoFR1** [ElectricGun/Toggle-Editor-Mode#4]
With this mod loaded, in the editor when you use the "Edit in-game" option, the game crash.

I did try without any mod, the crash only occurs with this one.

[crash_1687032847568.txt](https://github.com/ElectricGun/Toggle-Editor-Mode/files/11780004/crash_1687032847568.txt)

**Comment by JojoFR1** [comment]
Fixed 2 weeks ago

**Comment by LogicalMelon151** [comment]
yay :D
